---
compose_vmware_tag_ansible_groups_traefik:
  traefik:
    version: 2.2.0
    mounts:
      app:
        local: /mnt/traefik
        container: /etc/traefik
    selinux: ":Z"
    images:
      app: "{{ docker_registry }}/traefik:2.2.0"
    ports:
      https:
        protocol: tcp
        host: 443
        container: 443
      http:
        protocol: tcp
        host: 80
        container: 80
    do_token: "{{ lookup('onepassword', 'do-traefik-staging-api', field='password', vault='homelab') }}"
    le_email: acme@balmerfamilyfarm.com
    resolver1: 1.1.1.3:53 # TODO: To move these to the internal DoH, need to add traefik to that network somehow
    resolver2: 1.0.0.3:53