---
compose_vmware_tag_ansible_groups_gitea:
  gitea:
    mounts:
      app:
        local: /mnt/gitea/app
        remote: "{{ nfs_server }}:/mnt/POOL_A/docker/gitea/app"
      db:
        local: /mnt/gitea/db
        remote: "{{ nfs_server }}:/mnt/POOL_A/docker/gitea/db"
    images:
      app: "{{ docker_registry }}/gitea/gitea:1.13.1"
      db: "{{ docker_registry }}/postgres:11.10"
    ports:
      ssh:
        protocol: tcp
        host: 222
        container: 22
    version: 1.13.1
    user: 1012
    group: 1014
    http_port: 3000
    domain: git.balmerfamilyfarm.com
    postgres_version: "11.10"
    db_user: "{{ lookup('onepassword', 'ops-gitea-1', section='db', field='username', vault='homelab') }}"
    db_pass: "{{ lookup('onepassword', 'ops-gitea-1', section='db', field='password', vault='homelab') }}"
    db_name: gitea