---
compose_vmware_tag_ansible_groups_wikijs:
  wikijs:
    mounts:
      app:
        local: /mnt/wikijs/app
        remote: "{{ nfs_server }}:/mnt/POOL_A/docker/wikijs/app"
      db:
        local: /mnt/wikijs/db
        remote: "{{ nfs_server }}:/mnt/POOL_A/docker/wikijs/db"
    images:
      app: "{{ docker_registry }}/chrisbalmer/wiki:2.5.170"
      db: "{{ docker_registry }}/postgres:13.2"
    user: 1012
    group: 1014
    http_port: 3000
    domain: wiki.balmerfamilyfarm.com
    db_user: "{{ lookup('onepassword', 'WikiJS Accounts', section='db', field='username', vault='homelab') }}"
    db_pass: "{{ lookup('onepassword', 'WikiJS Accounts', section='db', field='password', vault='homelab') }}"
    db_name: wikijs