mirrors:
  - name: ansible_base
    description: CentOS-7 - Base
    protocol: http
    url: "mirror.balmerfamilyfarm.com/centos/7/os/x86_64/"
    directory: centos/7/base/x86_64
  - name: ansible_updates
    description: CentOS-7 - Updates
    protocol: http
    url: "mirror.balmerfamilyfarm.com/centos/7/updates/x86_64/"
    directory: centos/7/updates/x86_64
  - name: ansible_extras
    description: CentOS-7 - Extras
    protocol: http
    url: "mirror.balmerfamilyfarm.com/centos/7/extras/x86_64/"
    directory: centos/7/extras/x86_64
  - name: ansible_centosplus
    description: CentOS-7 - Plus
    protocol: http
    url: "mirror.balmerfamilyfarm.com/centos/7/centosplus/x86_64/"
    directory: centos/7/centosplus/x86_64
  - name: ansible_epel
    description: Extra Packages for Enterprise Linux 7 - x86_64
    protocol: http
    url: "mirror.balmerfamilyfarm.com/epel/7/x86_64/"
    directory: epel/7/x86_64