---
pihole_name: pihole
pihole_path: /var/pihole

conditional_forwards:
  - domain: oakops.io
    server: 172.21.7.254
  - domain: balmerfamilyfarm.com
    server: 172.21.7.254
  - domain: family.cloudflare-dns.com
    server: 1.1.1.3
  - domain: family.cloudflare-dns.com
    server: 1.0.0.3
